apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: yrkesskade-saksbehandling-backend
  namespace: yrkesskade
  labels:
    team: yrkesskade
spec:
  image: {{image}}
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{springProfile}}
    - name: GCP_PROJECT_ID
      value: {{gcpProjectId}}
  envFrom:
    - secret: yrkesskade-serviceuser
  liveness:
    path: /internal/health
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: /internal/health
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 2000m
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 1024Mi
  ingresses: 
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: yrkesskade-saksbehandling
            envVarPrefix: YRKESSKADE_SAKSBEHANDLING_DB
    bigQueryDatasets:
      - name: yrkesskade_metrikker
        permission: READWRITE
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: yrkesskade-saksbehandling
      external:
        {{#each externalHosts}}
          - host: {{host}}
        {{/each}}
  kafka:
    pool: {{kafka_pool}}
  secureLogs:
    enabled: true