apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: yrkesskade-saksbehandling-backend
  namespace: yrkesskade
  labels:
    team: yrkesskade
spec:
  image: {{image}}
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{springProfile}}
    - name: GCP_PROJECT_ID
      value: {{gcpProjectId}}
  envFrom:
    - secret: yrkesskade-serviceuser
  liveness:
    path: /internal/health
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: /internal/health
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 2000m
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 1024Mi
  ingresses: 
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: yrkesskade-saksbehandling
            envVarPrefix: YRKESSKADE_SAKSBEHANDLING_DB
    bigQueryDatasets:
      - name: yrkesskade_metrikker
        permission: READWRITE
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "de44052d-b062-4497-89a2-0c85b935b808"  # 0000-GA-GOSYS_UTVIDET
          - id: "ea930b6b-9397-44d9-b9e6-f4cf527a632a"  # 0000-GA-Fortrolig_Adresse
          - id: "5ef775f2-61f8-4283-bf3d-8d03f428aa14"  # 0000-GA-Strengt_Fortrolig_Adresse
          - id: "044d1494-7e95-4392-86b1-555f4aa6d5c5"  # 0000-ga-eessi-clerk-yrkesskade
          - id: "3db683fb-ba0d-4d1a-aa92-153b101d9c88"  # 0000-GA-EnGangIAaret
          - id: "dec3ee50-b683-4644-9507-520e8f054ac2"  # GRP Alle brukere
  accessPolicy:
    inbound:
      rules:
        - application: yrkesskade-saksbehandling
      external:
        {{#each externalHosts}}
          - host: {{host}}
        {{/each}}
    outbound:
      external:
        - host: unleash.nais.io
        {{#each outboundExternalHosts}}
        - host: {{host}}
        {{#if ports}}
          ports:
          {{#each ports}}
            - name: {{name}}
              port: {{port}}
              protocol: {{protocol}}
          {{/each}}
        {{/if}}
      {{/each}}
  kafka:
    pool: {{kafka_pool}}
  secureLogs:
    enabled: true