SAKSBEHANDLING_CLIENT_ID: ${AZURE_APP_CLIENT_ID}
TENANT_ID: 62366534-1ec3-4962-8869-9b5535279d0b         # nav.no

spring:
  kafka:
    properties:
      schema.registry.url: ${KAFKA_SCHEMA_REGISTRY}
      security.protocol: SSL
      basic:
        auth:
          credentials.source: USER_INFO
          user.info: ${KAFKA_SCHEMA_REGISTRY_USER}:${KAFKA_SCHEMA_REGISTRY_PASSWORD}
      ssl:
        truststore:
          type: JKS
          location: ${KAFKA_TRUSTSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        keystore:
          type: PKCS12
          location: ${KAFKA_KEYSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        key.password: ${KAFKA_CREDSTORE_PASSWORD}

no.nav.security.jwt:
  client:
    registration:
      dokarkiv-maskintilmaskin:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://${api.client.dokarkiv.clientId}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt
      saf-maskintilmaskin:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://${api.client.saf.clientId}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt
      saf-onbehalfof:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: api://${api.client.saf.clientId}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt
      pdl-onbehalfof:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: api://${api.client.pdl.clientId}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt
      pdl-maskintilmaskin:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://${api.client.pdl.clientId}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt
      kodeverk-maskintilmaskin:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://${api.client.kodeverk.clientId}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt

funksjonsbrytere:
  enabled: false

kafka:
  topic:
    dokument-til-saksbehandling:
      name: yrkesskade.privat-yrkesskade-dokument-til-saksbehandling
      auto-startup: false
    brevutsending-utfoert:
      name: yrkesskade.privat-yrkesskade-brevutsending-utfoert
      auto-startup: false
    aapen-oppgave-opprettet: aapen-oppgave-opprettet-v1-local
    aapen-oppgave-endret: aapen-oppgave-endret-v1-local

rolle:
  saksbehandler: 70bc7d4d-1cb3-4240-8f02-1a1b46d9e7a3
  kode6: ad7b87a6-9180-467c-affc-20a566b0fec0
  kode7: 9ec6487d-f37a-4aad-a027-cd221c1ac32b

api:
  client:
    dokarkiv:
      clientId: prod-fss.teamdokumenthandtering.dokarkiv
      url: https://dokarkiv.prod-fss-pub.nais.io
    kodeverk:
      clientId: prod-gcp.yrkesskade.yrkesskade-kodeverk
      url: https://yrkesskade-kodeverk.intern.nav.no
    json-to-pdf:
      url: https://yrkesskade-json-to-pdf.intern.nav.no
    pdl:
      clientId: prod-fss.pdl.pdl-api
      url: https://pdl-api.prod-fss-pub.nais.io
    oppgave:
      clientId: 50346823-61a0-49e7-ad89-ea2b1a0e90f8
      url: https://oppgave.prod-fss-pub.nais.io