NAIS_CLUSTER_NAME: lokal
KAFKA_BROKERS: http://localhost:9092
SAKSBEHANDLING_CLIENT_ID: api://dev-gcp.yrkesskade.yrkesskade-saksbehandling-backend/.default

server:
  port: 9081

AZURE_APP_WELL_KNOWN_URL: https://fakedings.dev-gcp.nais.io/fake/.well-known/openid-configuration

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="igroup" password="itest";
      schema.registry.url: http://localhost:8081
    consumer:
      group-id: srvc01
  datasource:
    url: jdbc:postgresql://localhost:5432/yrkesskade_saksbehandling
  flyway:
    enabled: true

funksjonsbrytere:
  enabled: false

kafka:
  topic:
    aapen-oppgave-opprettet: aapen-oppgave-opprettet-v1-local
    aapen-oppgave-endret: aapen-oppgave-endret-v1-local