NAIS_CLUSTER_NAME: lokal
KAFKA_BROKERS: http://localhost:9092
SAKSBEHANDLING_CLIENT_ID: api://dev-gcp.yrkesskade.yrkesskade-saksbehandling-backend/.default
AUTH_SERVER: https://fakedings.dev-gcp.nais.io/fake
AZURE_APP_JWK: local
AZURE_APP_WELL_KNOWN_URL: https://fakedings.dev-gcp.nais.io/fake/.well-known/openid-configuration

server:
  port: 9081

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="igroup" password="itest";
      schema.registry.url: http://localhost:8081
    consumer:
      group-id: srvc01
  datasource:
    url: jdbc:postgresql://localhost:5432/yrkesskade_saksbehandling
  flyway:
    enabled: true


funksjonsbrytere:
  enabled: false

kafka:
  topic:
    dokument-til-saksbehandling:
      name: privat-yrkesskade-dokument-til-saksbehandling
    brevutsending-bestilt: privat-yrkesskade-brevutsending-bestilt
    aapen-oppgave-opprettet: aapen-oppgave-opprettet-v1-local
    aapen-oppgave-endret: aapen-oppgave-endret-v1-local

no.nav.security.jwt:
  issuer:
    azuread:
      discovery-url: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${SAKSBEHANDLING_CLIENT_ID}
      cookie_name: auth_token
  client:
    registration:
      saf-maskintilmaskin:
        token-endpoint-url: ${AUTH_SERVER}/aad
        grant-type: client_credentials
        scope: saf
        authentication:
          client-id: dummy-client-id
          client-secret: dummy-secret
          client-auth-method: client_secret_basic
      pdl-onbehalfof:
        token-endpoint-url: ${AUTH_SERVER}/aad
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: pdl
        authentication:
          client-id: dummy-client-id
          client-secret: dummy-secret
          client-auth-method: client_secret_basic
      pdl-clientcredentials:
        token-endpoint-url: ${AUTH_SERVER}/aad
        grant-type: client_credentials
        scope: pdl
        authentication:
          client-id: dummy-client-id
          client-secret: dummy-secret
          client-auth-method: client_secret_basic

rolle:
  saksbehandler: 044d1494-7e95-4392-86b1-555f4aa6d5c5
  kode6: 5ef775f2-61f8-4283-bf3d-8d03f428aa14
  kode7: ea930b6b-9397-44d9-b9e6-f4cf527a632a

YRKESSKADE_DOKGEN_API_URL: http://localhost:5914
YRKESSKADE_KODEVERK_API_URL: http://localhost:8080
PDL_URL: https://pdl-api.default
