SAKSBEHANDLING_CLIENT_ID: ${AZURE_APP_CLIENT_ID}
TENANT_ID: 966ac572-f5b7-4bbe-aa88-c76419c0f851

spring:
  application:
    name: yrkesskade-saksbehandling-backend
    main:
      banner-mode: off
      allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    client-id: yrkesskade-saksbehandling
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: yrkesskade-saksbehandling
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: no.nav.yrkesskade.saksbehandling.model
        isolation.level: read_committed
    listener:
      ack-mode: record
  datasource:
    url: jdbc:postgresql://${YRKESSKADE_SAKSBEHANDLING_DB_HOST}:${YRKESSKADE_SAKSBEHANDLING_DB_PORT}/${YRKESSKADE_SAKSBEHANDLING_DB_DATABASE}
    username: ${YRKESSKADE_SAKSBEHANDLING_DB_USERNAME}
    password: ${YRKESSKADE_SAKSBEHANDLING_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-test-query: "select 1"
      max-lifetime: 30000
      minimum-idle: 1
      data-source-properties.stringtype: unspecified # Nødvendig for å kunde sende en String til et json-felt i PostgresSql
  flyway:
    enabled: true
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        ddl-auto: none

no.nav.security.jwt:
  issuer:
    azuread:
      discovery-url: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${SAKSBEHANDLING_CLIENT_ID}
      cookie_name: azure_token

graphql:
  servlet:
    enabled: true
    cors-enabled: true
    cors:
      allowed-origins: '*'
      allowed-methods: GET, HEAD, POST
    websocket:
      enabled: false
    mapping: /api/graphql
    actuator-metrics: true
    async-mode-enabled: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
      base-path: /internal
      path-mapping.prometheus: prometheus
  metrics:
    export.prometheus.enabled: true
    tags:
      application: ${spring.application.name}

kafka:
  topic:
    dokument-til-saksbehandling:
      name: privat-yrkesskade-dokument-til-saksbehandling
    brevutsending-bestilt: privat-yrkesskade-brevutsending-bestilt
    aapen-oppgave-opprettet: aapen-oppgave-opprettet-v1-preprod
    aapen-oppgave-endret: aapen-oppgave-endret-v1-preprod

saf:
  rest.url: https://saf-q1.dev.intern.nav.no/
  graphql.url: https://saf.dev-fss-pub.nais.io/graphql

funksjonsbrytere:
  enabled: true
  unleash:
    uri: https://unleash.nais.io/api/
    cluster: ${NAIS_CLUSTER_NAME}
    applicationName: ${spring.application.name}

SAF_APP_CLIENT_ID: dev-fss.teamdokumenthandtering.saf
