SAKSBEHANDLING_CLIENT_ID: ${AZURE_APP_CLIENT_ID}
TENANT_ID: 966ac572-f5b7-4bbe-aa88-c76419c0f851         # trygdeetaten.no
PDL_SCOPE: api://dev-fss.pdl.pdl-api/.default

spring:
  kafka:
    properties:
      schema.registry.url: ${KAFKA_SCHEMA_REGISTRY}
      security.protocol: SSL
      basic:
        auth:
          credentials.source: USER_INFO
          user.info: ${KAFKA_SCHEMA_REGISTRY_USER}:${KAFKA_SCHEMA_REGISTRY_PASSWORD}
      ssl:
        truststore:
          type: JKS
          location: ${KAFKA_TRUSTSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        keystore:
          type: PKCS12
          location: ${KAFKA_KEYSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        key.password: ${KAFKA_CREDSTORE_PASSWORD}


no.nav.security.jwt:
  client:
    registration:
      dokarkiv-maskintilmaskin:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://${api.client.dokarkiv.clientId}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt
      saf-maskintilmaskin:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://${SAF_APP_CLIENT_ID}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt
      pdl-onbehalfof:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${PDL_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt
      pdl-clientcredentials:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: ${PDL_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt

funksjonsbrytere:
  enabled: false

kafka:
  topic:
    dokument-til-saksbehandling:
      name: yrkesskade.privat-yrkesskade-dokument-til-saksbehandling
    aapen-oppgave-opprettet: aapen-oppgave-opprettet-v1-local
    aapen-oppgave-endret: aapen-oppgave-endret-v1-local

rolle:
  saksbehandler: 044d1494-7e95-4392-86b1-555f4aa6d5c5
  kode6: 5ef775f2-61f8-4283-bf3d-8d03f428aa14
  kode7: ea930b6b-9397-44d9-b9e6-f4cf527a632a