apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: privat-yrkesskade-brevutsending-bestilt
  namespace: yrkesskade
  labels:
    team: yrkesskade
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 336
  acl:
    - team: yrkesskade
      application: yrkesskade-saksbehandling-backend
      access: write
    - team: yrkesskade
      application: yrkesskade-brevutsending
      access: read
