CREATE TABLE sak
(
    sak_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saksstatus           VARCHAR(50)  NOT NULL,
    opprettet_tidspunkt  TIMESTAMP    NOT NULL,
    opprettet_av         VARCHAR(255) NOT NULL,
    sakstype             VARCHAR(50)  NOT NULL,
    aktoer_id            VARCHAR(20)  NOT NULL, -- brukes av flere systemer i NAV
    bruker_identifikator VARCHAR(12)  NOT NULL, -- fnr/dnr
    bruker_fornavn       VARCHAR(100) NOT NULL,
    bruker_mellomnavn    VARCHAR(100),
    bruker_etternavn     VARCHAR(100) NOT NULL
);

CREATE TABLE behandling
(
    behandling_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    behandlingsansvarlig_ident VARCHAR(255),          -- ident til saksbehandler
    status                     VARCHAR(50)  NOT NULL,
    statuskategori             VARCHAR(50)  NOT NULL,
    ansvarlig_enhet            VARCHAR(100) NOT NULL, -- kode til behandlingsenhet
    sak_id                     BIGINT       NOT NULL,
    oppgave_id                 VARCHAR(100) NOT NULL,
    oppgave_type               VARCHAR(100) NOT NULL,
    frist_ferdigstillelse      TIMESTAMP    NOT NULL,
    opprettet_tidspunkt        TIMESTAMP    NOT NULL,
    aktiv_dato                 TIMESTAMP    NOT NULL,
    behandlingstema            VARCHAR(100) NOT NULL,
    opprettet_av               VARCHAR(255) NOT NULL,
    endret_av                  VARCHAR(255),
    CONSTRAINT fk_sak_id FOREIGN KEY (sak_id) REFERENCES sak (sak_id) ON DELETE CASCADE
);

CREATE TABLE dokument
(
    dokument_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journalpost_id        varchar(255) NOT NULL,
    dokument_navn          VARCHAR(255) NOT NULL,
    dokument_type          VARCHAR(50)  NOT NULL,
    dokument_kategori      VARCHAR(50)  NOT NULL,
    opprettet_tidspunkt    TIMESTAMP    NOT NULL,
    avsender_identifikator VARCHAR(12)  NOT NULL,
    avsender_rolle         VARCHAR(100) NOT NULL,
    behandling_id          BIGINT,
    CONSTRAINT fk_behandling_id FOREIGN KEY (behandling_id) REFERENCES behandling (behandling_id) ON DELETE CASCADE
);

CREATE TABLE dokumentfil
(
    fil_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    navn              varchar(255) NOT NULL,
    type              VARCHAR(50)  NOT NULL,
    vedlegg_referanse VARCHAR(255) NOT NULL,
    status            VARCHAR(100) NOT NULL,
    dokument_id       BIGINT       NOT NULL,
    CONSTRAINT fk_dokument_id FOREIGN KEY (dokument_id) REFERENCES dokument (dokument_id) ON DELETE CASCADE
);

-- 1-til-1 relasjon? - En behandling kan ha ett resultat?
CREATE TABLE behandlingsresultat
(
    behandlingsresultat_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    behandling_id          BIGINT       NOT NULL,
    resultat_tidspunkt     TIMESTAMP    NOT NULL,
    sted                   VARCHAR(255) NOT NULL,
    bakgrunnsaarsak        TEXT         NOT NULL,
    utfyllende_beskrivelse TEXT         NOT NULL,
    CONSTRAINT fk_behandling_id FOREIGN KEY (behandling_id) REFERENCES behandling (behandling_id) ON DELETE CASCADE
);










