-- Oppretter en tabell for logg av behandlingsoverføring fra dette
-- systemet til andre systemer
CREATE TABLE behandlingsoverforing_log
(
    overfoering_log_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    overfoert_tidspunkt     TIMESTAMP    NOT NULL,
    overfoert_av            VARCHAR(100) NOT NULL,
    journalpost_id          VARCHAR(100) NOT NULL,
    avviksbegrunnelse       VARCHAR(255) NOT NULL,
    behandlingstype         VARCHAR(100) NOT NULL,
    overfoert_til_system    VARCHAR(100) NOT NULL
);