CREATE TABLE skademelding (
	skademelding_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- innmelder
    innmelder_identitetsnummer VARCHAR(15) NOT NULL,
  	innmelder_paa_vegne_av VARCHAR (15) NOT NULL,
  	innmelder_virksomhetsnavn VARCHAR (255) NOT NULL DEFAULT '',
  	innmelder_rolle VARCHAR (200) NOT NULL,
  	tidspunkt_mottatt TIMESTAMP NOT NULL,
  	-- innmelder_altinn_roller
  -- skadelidt
    skadelidt_identitetsnummer VARCHAR (15),
  	skadelidt_rolletype VARCHAR (100) NOT NULL,
  -- dekningsforhold
  	dekning_organisasjonsnummer VARCHAR (15) NOT NULL,
  	dekning_navn_paa_virksomheten VARCHAR (255) NOT NULL DEFAULT '',
  -- skade
  	skade_alvorlighetsgrad VARCHAR (100) NOT NULL,
  	skade_fravaertype VARCHAR (100),
  -- hendelse
	hendelse_naar_skjedde_ulykken VARCHAR (100) NOT NULL,
  	hendelse_hvor_skjedde_ulykken VARCHAR (100) NOT NULL,
  	hendelse_utfyllende_beskrivelse VARCHAR (2000) NOT NULL,
  	hendelse_steds_beskrivelse VARCHAR (100) NOT NULL,
  -- tid
  	hendelse_tidstype VARCHAR (100) NOT NULL, -- TIDSPUNKT | PERIODE | UKJENT
  	hendelse_tidspunkt TIMESTAMP,
  	hendelse_periode_fra TIMESTAMP,
  	hendelse_periode_til TIMESTAMP
 );

CREATE TABLE skademelding_hendelse_bakgrunn_ulykke (
    skademelding_id BIGINT NOT NULL,
    bakgrunn_ulykke VARCHAR (100) NOT NULL,
    PRIMARY KEY (skademelding_id, bakgrunn_ulykke),
    CONSTRAINT fk_skademelding_id FOREIGN KEY(skademelding_id) REFERENCES skademelding(skademelding_id) ON DELETE CASCADE
);

CREATE TABLE skademelding_hendelse_aarsak_ulykke (
    skademelding_id BIGINT NOT NULL,
    aarsak_ulykke VARCHAR (100) NOT NULL,
    PRIMARY KEY (skademelding_id, aarsak_ulykke),
    CONSTRAINT fk_skademelding_id FOREIGN KEY(skademelding_id) REFERENCES skademelding(skademelding_id) ON DELETE CASCADE
);

CREATE TABLE skademelding_skadelidt_stilling (
  skademelding_id BIGINT NOT NULL,
  stillingstittel VARCHAR (300) NOT NULL,
  PRIMARY KEY (skademelding_id, stillingstittel),
  CONSTRAINT fk_skademelding_id FOREIGN KEY(skademelding_id) REFERENCES skademelding(skademelding_id) ON DELETE CASCADE
);

CREATE TABLE skademelding_virksomhetsadresse (
  	skademelding_id BIGINT PRIMARY KEY,
	adresselinje_1 VARCHAR (255) NOT NULL,
    adresselinje_2 VARCHAR (255) NOT NULL,
    adresselinje_3 VARCHAR (255) NOT NULL,
  	landkode VARCHAR (3) NOT NULL,
  	CONSTRAINT fk_skademelding_id FOREIGN KEY(skademelding_id) REFERENCES skademelding(skademelding_id) ON DELETE CASCADE
);

CREATE TABLE skademelding_ulykkessted (
  	skademelding_id BIGINT PRIMARY KEY,
  	samme_som_virksomhetens_adresse BOOLEAN NOT NULL,
	adresselinje_1 VARCHAR (255) NOT NULL,
    adresselinje_2 VARCHAR (255) NOT NULL,
    adresselinje_3 VARCHAR (255) NOT NULL,
  	landkode VARCHAR (3) NOT NULL,
  	CONSTRAINT fk_skademelding_id FOREIGN KEY(skademelding_id) REFERENCES skademelding(skademelding_id) ON DELETE CASCADE
);

CREATE TABLE skademelding_bostedsadresse (
  	skademelding_id BIGINT PRIMARY KEY,
	adresselinje_1 VARCHAR (255) NOT NULL,
    adresselinje_2 VARCHAR (255) NOT NULL,
    adresselinje_3 VARCHAR (255) NOT NULL,
  	landkode VARCHAR (3) NOT NULL,
  	CONSTRAINT fk_skademelding_id FOREIGN KEY(skademelding_id) REFERENCES skademelding(skademelding_id) ON DELETE CASCADE
);

CREATE TABLE skadet_del (
  	skademelding_id BIGINT,
  	skadeart VARCHAR (100) NOT NULL,
  	kroppsdel VARCHAR (100) NOT NULL,
  	PRIMARY KEY (skademelding_id, skadeart, kroppsdel),
  	CONSTRAINT fk_skademelding_id FOREIGN KEY(skademelding_id) REFERENCES skademelding(skademelding_id) ON DELETE CASCADE
);







